### ISSUE TITLE
Timer for discussions

### ISSUE THREAD

**Issue by an-ju** [adnanhemani/planning-poker#18]
In order to better manifest the idea of scaffolding, we'd like to add a timer to the discussion step, such that students will understand that they shouldn't spend too much time on discussions.

**Comment by an-ju** [comment]
A UI draft can be found in this [doc](https://docs.google.com/presentation/d/1SWY0BrEvuFclxaOarQQV2J2feBOlaeNtoVLR89qwYwg/edit?usp=sharing).

**Comment by adnanhemani** [comment]
Added PR #19 as first draft

**Comment by adnanhemani** [comment]
Merged PR #19.
