### ISSUE TITLE
Outdated Pivotal Tracker gem

### ISSUE THREAD

**Issue by an-ju** [adnanhemani/planning-poker#3]
The Pivotal Tracker gem is outdated (it uses API v3, while the latest is v5).

Luckily there aren't many usages of the gem's APIs, so we can replace this gem with a new gem or our own API library.

**Comment by adnanhemani** [comment]
The new gem I integrated should be using API v5

**Comment by an-ju** [comment]
The description is updated.

**Comment by adnanhemani** [comment]
Fixed by PR #4
